name: Build macOS ARM64
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  workflow_dispatch:

env:
  BUILD_XCODE_PATH: /Applications/Xcode_26.0.app
  RUNNER_IMAGE: macos-15
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 60

jobs:
  configuration:
    name: Setup configuration
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.checker.outputs.runners }}
      github-runner: ${{ steps.checker.outputs.github-runner }}
    steps:
    - name: Check for hosted runners
      id: checker
      shell: bash
      env:
        IS_SELF_HOSTED_RUNNER: ${{ vars.IS_SELF_HOSTED_RUNNER || (github.repository_owner == 'utmapp' && 'true') }}
      run: |
        echo "github-runner='$RUNNER_IMAGE'" >> $GITHUB_OUTPUT
        if [ "$IS_SELF_HOSTED_RUNNER" == "true" ]; then
          echo "runners=['self-hosted', 'macOS']" >> $GITHUB_OUTPUT
        else
          echo "runners='$RUNNER_IMAGE'" >> $GITHUB_OUTPUT
        fi

  build-sysroot:
    name: Build Sysroot (macOS arm64)
    runs-on: ${{ fromJSON(needs.configuration.outputs.runner) }}
    needs: configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Xcode
        shell: bash
        run: |
          [[ "$(xcode-select -p)" == "${{ env.BUILD_XCODE_PATH }}"* ]] || sudo xcode-select -s "${{ env.BUILD_XCODE_PATH }}"
      - name: Check Cache
        id: cache-sysroot
        uses: actions/cache/restore@v4
        with:
          path: ./sysroot-macos-arm64
          key: macos-arm64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}-${{ github.sha }}
          restore-keys: macos-arm64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Setup Path
        shell: bash
        run: |
          echo "/usr/local/opt/bison/bin:/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH
      - name: Install Build Tools
        run: |
          brew install bison pkg-config gettext glib-utils libgpg-error nasm meson cmake libclc spirv-llvm-translator spirv-tools libpsl libxcb libxrandr 2>/dev/null || true
          rm -f /usr/local/lib/pkgconfig/*.pc
      - name: Install Python Requirements
        run: |
          pip3 install --break-system-packages --user six pyparsing pyyaml setuptools distlib mako
      - name: Install XCPretty
        if: steps.cache-sysroot.outputs.cache-matched-key == '' || github.event.inputs.rebuild_sysroot == 'true'
        run: |
          brew uninstall cmake || true
          brew install cmake || true
          gem install --user-install xcpretty
      - name: Build Sysroot
        if: steps.cache-sysroot.outputs.cache-matched-key == ''
        run: ./scripts/build_dependencies.sh -p macos -a arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compress Sysroot
        if: steps.cache-sysroot.outputs.cache-matched-key == '' || github.event_name == 'release' || github.event.inputs.test_release == 'true'
        run: tar -acf sysroot.tgz sysroot*
      - name: Upload Sysroot
        if: steps.cache-sysroot.outputs.cache-matched-key == '' || github.event_name == 'release' || github.event.inputs.test_release == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Sysroot-macos-arm64
          path: sysroot.tgz
      - name: Save Cache
        if: steps.cache-sysroot.outputs.cache-matched-key == ''
        uses: actions/cache/save@v4
        with:
          path: ./sysroot-macos-arm64
          key: ${{ steps.cache-sysroot.outputs.cache-primary-key }}
          upload-chunk-size: 1048576 # 1 MiB

  build-utm:
    name: Build UTM (macOS arm64)
    runs-on: ${{ fromJSON(needs.configuration.outputs.runner) }}
    needs: [configuration, build-sysroot]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache Sysroot
        id: cache-sysroot
        uses: actions/cache/restore@v4
        with:
          path: ./sysroot-macos-arm64
          key: macos-arm64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
          fail-on-cache-miss: true
      - name: Setup Xcode
        shell: bash
        run: |
          [[ "$(xcode-select -p)" == "${{ env.BUILD_XCODE_PATH }}"* ]] || sudo xcode-select -s "${{ env.BUILD_XCODE_PATH }}"
      - name: Build UTM
        run: |
          ./scripts/build_utm.sh -k macosx -s macOS -a arm64 -o UTM
          tar -acf UTM.xcarchive.tgz UTM.xcarchive
      - name: Upload UTM
        uses: actions/upload-artifact@v4
        with:
          name: UTM-macos-arm64
          path: UTM.xcarchive.tgz
